// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbguqeqdbaouozflatle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZ3VxZXFkYmFvdW96ZmxhdGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjY4MzMsImV4cCI6MjA3MTEwMjgzM30.zszKcq2BWgDshMewKS_Pkk6cRT2-PUMRd663wfHMtpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});